PROGRAM MAIN
  INTEGER :: NSTEP, NSTEPMAX, ERR, MYPROC
  INTEGER :: NPROMA, LAST_BLK_NPROMA, NFLEV, NBLKS, GRID
  CHARACTER(LEN=8) :: NPROMA_STR
  LOGICAL :: FILE_EXIST
  NSTEPMAX = 89
  GRID=1784
  NFLEV=15

  IF(COMMAND_ARGUMENT_COUNT() /= 1)THEN
    WRITE(*,*)"USAGE: ./MAIN.X NPROMA"
    STOP 1
  ENDIF

  INQUIRE(FILE="DATA/ACVPPKF.IN.DAT", EXIST=FILE_EXIST)
  IF(.NOT. FILE_EXIST)THEN
    WRITE(*,*)"COULDN'T FIND INPUT FILE DATA/ACVPPKF.IN.DAT"
    STOP 1
  ENDIF
  INQUIRE(FILE="DATA/ACVPPKF.OUT.DAT", EXIST=FILE_EXIST)
  IF(.NOT. FILE_EXIST)THEN
    WRITE(*,*)"COULDN'T FIND INPUT FILE DATA/ACVPPKF.OUT.DAT"
    STOP 1
  ENDIF
  INQUIRE(FILE="DATA/ACVPPKF.CONST.DAT", EXIST=FILE_EXIST)
  IF(.NOT. FILE_EXIST)THEN
    WRITE(*,*)"COULDN'T FIND INPUT FILE DATA/ACVPPKF.CONST.DAT"
    STOP 1
  ENDIF

  CALL GET_COMMAND_ARGUMENT(1, NPROMA_STR)
  READ(NPROMA_STR, *) NPROMA

  IF(MOD(GRID, NPROMA) ==0)THEN
    NBLKS=GRID/NPROMA
    LAST_BLK_NPROMA=NPROMA
  ELSE
    NBLKS=GRID/NPROMA +1
    LAST_BLK_NPROMA=MOD(GRID, NPROMA)
  ENDIF

  WRITE(*,*)"GRID SIZE",GRID
  WRITE(*,*)"NPROMA", NPROMA
  WRITE(*,*)"NBLKS:",NBLKS
  WRITE(*,*)"NPROMA OF LAST BLOCK", LAST_BLK_NPROMA

  CALL WRAP_ACVPPKF(NSTEPMAX, NPROMA, LAST_BLK_NPROMA, NFLEV, NBLKS)
END PROGRAM MAIN
