PROGRAM MAIN
  INTEGER :: NSTEP, NSTEPMAX, ERR, MYPROC
  INTEGER :: NPROMA, LAST_BLK_NPROMA, NFLEV, NBLKS, GRID
  NSTEPMAX = 89
  GRID=1784
  NPROMA=1784
  NFLEV=15
  IF(MOD(GRID, NPROMA) ==0)THEN
    NBLKS=GRID/NPROMA
    LAST_BLK_NPROMA=NPROMA
  ELSE
    NBLKS=GRID/NPROMA +1
    LAST_BLK_NPROMA=MOD(GRID, NPROMA)
  ENDIF

  WRITE(*,*)"GRID SIZE",GRID
  WRITE(*,*)"NPROMA", NPROMA
  WRITE(*,*)"NBLKS:",NBLKS
  WRITE(*,*)"NPROMA OF LAST BLOCK", LAST_BLK_NPROMA

  CALL WRAP_ACVPPKF(NSTEPMAX, NPROMA, LAST_BLK_NPROMA, NFLEV, NBLKS)
END PROGRAM MAIN
