INTERFACE
SUBROUTINE ACVPPKF( YDCST,YDML_PHY_MF,CST,D,KTDIA,&
 & PAPRSF, PAPHIF, PDELP, PR, PT, PQ,&
 & PQL, PQI, PU, PV, PCP, PTKE,&
 & PDIFCQ, PDIFCS, PFCCQL, PFCCQN, PPRODTH,&
 & KNLAB, PQCPP, PNEBPP,&
 & KNND) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCST , ONLY : TCST
USE MODD_CST, ONLY: CST_T
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
TYPE(CST_T),INTENT(IN):: CST
TYPE(DIMPHYEX_t),INTENT(INOUT):: D
INTEGER(KIND=JPIM) ,INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PR (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PT (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PQL (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PQI (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PU (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PV (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(IN) :: PTKE (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFCQ (D%NIE,0:D%NKT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFCS (D%NIE,0:D%NKT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCCQL (D%NIE,0:D%NKT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCCQN (D%NIE,0:D%NKT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPRODTH(D%NIE,0:D%NKT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQCPP (D%NIE,D%NKT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEBPP (D%NIE,D%NKT)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KNLAB (D%NIE,D%NKT)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KNND (D%NIE)
END SUBROUTINE ACVPPKF
END INTERFACE
