INTERFACE

SUBROUTINE ACVPPKF(YDCST,YDML_PHY_MF,CST,D,NSV,CONVPAR,KTDIA, &
& PAPRSF, PAPHIF, PDELP, PR, PT, PQ, &
& PQL, PQI, PU, PV, PCP, PTKE, &
& PDIFCQ, PDIFCS, PFCCQL, PFCCQN, PPRODTH, &
& KNLAB, PQCPP, PNEBPP,&
& KNND)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE YOMCST  , ONLY :  TCST
USE YOMLSFORC, ONLY : LMUSCLFA,NMUSCLFA
USE MODD_CONVPAR, ONLY : CONVPAR_T
USE MODD_CONVPAR_SHAL, ONLY : CONVPAR_SHAL
USE MODD_CST, ONLY: CST_T
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
USE MODD_NSV, ONLY: NSV_T
TYPE(TCST)         ,INTENT (IN)   :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
TYPE(CST_T)        ,INTENT(IN)    :: CST
TYPE(DIMPHYEX_T)   ,INTENT(IN)    :: D
TYPE(NSV_T)        ,INTENT(IN)    :: NSV
TYPE(CONVPAR_T)    ,INTENT(IN)    :: CONVPAR
INTEGER(KIND=JPIM) ,INTENT(IN)    :: KTDIA
REAL(KIND=JPRB)    ,INTENT(IN)    :: PAPRSF (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PAPHIF (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PDELP  (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PR     (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PT     (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PQ     (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PQL    (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PQI    (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PU     (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PV     (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PCP    (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(IN)    :: PTKE   (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(INOUT) :: PDIFCQ (D%NIT,0:D%NKT)
REAL(KIND=JPRB)    ,INTENT(INOUT) :: PDIFCS (D%NIT,0:D%NKT)
REAL(KIND=JPRB)    ,INTENT(INOUT) :: PFCCQL (D%NIT,0:D%NKT)
REAL(KIND=JPRB)    ,INTENT(INOUT) :: PFCCQN (D%NIT,0:D%NKT)
REAL(KIND=JPRB)    ,INTENT(INOUT) :: PPRODTH(D%NIT,0:D%NKT)
REAL(KIND=JPRB)    ,INTENT(INOUT) :: PQCPP  (D%NIT,D%NKT)
REAL(KIND=JPRB)    ,INTENT(INOUT) :: PNEBPP (D%NIT,D%NKT)
INTEGER(KIND=JPIM) ,INTENT(OUT)   :: KNLAB  (D%NIT,D%NKT)
INTEGER(KIND=JPIM) ,INTENT(OUT)   :: KNND   (D%NIT)
END SUBROUTINE ACVPPKF

END INTERFACE
