INTERFACE
SUBROUTINE SHALLOW_CONVECTION_SELECT( CVP_SHAL, CVPEXT, CST, D, NSV,    &
ICONV, KICE, OSETTADJ,            &
PTADJS, PPABST, PZZ, PTT, PRVT,   &
PRCT, PRIT, PTTEN, PRVTEN, PRCTEN,&
PRITEN, KCLTOP, KCLBAS, PUMF,     &
OCH1CONV, KCH1, PCH1, PCH1TEN,    &
IKB, IKE, IFTSTEPS, PRDOCP, PTHT, &
PSTHV, PSTHES, ISDPL, ISPBL,      &
ISLCL, PSTHLCL, PSTLCL, PSRVLCL,  &
PSWLCL, PSZLCL, PSTHVELCL, GTRIG1)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE MODD_CONVPAR_SHAL, ONLY: CONVPAR_SHAL
USE MODD_CONVPAREXT, ONLY: CONVPAREXT
USE MODD_CST, ONLY: CST_T
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_T
USE MODD_NSV, ONLY: NSV_T
TYPE(CONVPAR_SHAL),              INTENT(IN)   :: CVP_SHAL
TYPE(CONVPAREXT),                INTENT(IN)   :: CVPEXT
TYPE(CST_T),                     INTENT(IN)   :: CST
TYPE(DIMPHYEX_T),                INTENT(IN)   :: D
TYPE(NSV_T),                     INTENT(IN)   :: NSV
INTEGER,                         INTENT(IN)   :: ICONV
INTEGER,                         INTENT(IN)   :: KICE
LOGICAL,                         INTENT(IN)   :: OSETTADJ
REAL,                            INTENT(IN)   :: PTADJS
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(IN)   :: PTT
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(IN)   :: PRVT
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(IN)   :: PRCT
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(IN)   :: PRIT
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(IN)   :: PPABST
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(IN)   :: PZZ
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(INOUT):: PTTEN
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(INOUT):: PRVTEN
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(INOUT):: PRCTEN
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(INOUT):: PRITEN
INTEGER, DIMENSION(D%NIT),        INTENT(INOUT):: KCLTOP
INTEGER, DIMENSION(D%NIT),        INTENT(INOUT):: KCLBAS
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(INOUT):: PUMF
LOGICAL,                         INTENT(IN)   :: OCH1CONV
INTEGER,                         INTENT(IN)   :: KCH1
REAL, DIMENSION(D%NIT,D%NKT,KCH1), INTENT(IN)   :: PCH1
REAL, DIMENSION(D%NIT,D%NKT,KCH1), INTENT(INOUT):: PCH1TEN
INTEGER, INTENT(IN)                           :: IKB, IKE
INTEGER, INTENT(INOUT)                        :: IFTSTEPS
REAL   , INTENT(IN)                           :: PRDOCP
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(IN)   :: PTHT, PSTHV, PSTHES
INTEGER, DIMENSION(D%NIT)  ,      INTENT(IN)   :: ISDPL
INTEGER, DIMENSION(D%NIT)  ,      INTENT(IN)   :: ISPBL
INTEGER, DIMENSION(D%NIT)  ,      INTENT(IN)   :: ISLCL
REAL, DIMENSION(D%NIT)     ,      INTENT(IN)   :: PSTHLCL
REAL, DIMENSION(D%NIT)     ,      INTENT(IN)   :: PSTLCL
REAL, DIMENSION(D%NIT)     ,      INTENT(IN)   :: PSRVLCL
REAL, DIMENSION(D%NIT)     ,      INTENT(IN)   :: PSWLCL
REAL, DIMENSION(D%NIT)     ,      INTENT(IN)   :: PSZLCL
REAL, DIMENSION(D%NIT)     ,      INTENT(IN)   :: PSTHVELCL
LOGICAL, DIMENSION(D%NIT)  ,      INTENT(INOUT):: GTRIG1
END SUBROUTINE SHALLOW_CONVECTION_SELECT

END INTERFACE
