    MODULE UTIL_MODD_CST
    USE MODD_CST
    INTEGER :: CHECK_REF = 123456789
    CONTAINS

    SUBROUTINE SAVE_MODD_CST(FH)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FH
    WRITE(FH) CHECK_REF

    WRITE(FH) XPI
    WRITE(FH) XDAY
    WRITE(FH) XSIYEA
    WRITE(FH) XSIDAY
    WRITE(FH) XKARMAN
    WRITE(FH) XLIGHTSPEED
    WRITE(FH) XPLANCK
    WRITE(FH) XBOLTZ
    WRITE(FH) XAVOGADRO
    WRITE(FH) XRADIUS
    WRITE(FH) XOMEGA
    WRITE(FH) XG
    WRITE(FH) XP00
    WRITE(FH) XSTEFAN
    WRITE(FH) XI0
    WRITE(FH) XMD
    WRITE(FH) XMV
    WRITE(FH) XRD
    WRITE(FH) XRV
    WRITE(FH) XEPSILO
    WRITE(FH) XCPD
    WRITE(FH) XCPV
    WRITE(FH) XRHOLW
    WRITE(FH) XCL
    WRITE(FH) XCI
    WRITE(FH) XTT
    WRITE(FH) XLVTT
    WRITE(FH) XLSTT
    WRITE(FH) XLMTT
    WRITE(FH) XESTT
    WRITE(FH) XALPW
    WRITE(FH) XBETAW
    WRITE(FH) XGAMW
    WRITE(FH) XALPI
    WRITE(FH) XBETAI
    WRITE(FH) XGAMI
    WRITE(FH) XCONDI
    WRITE(FH) XTH00
    WRITE(FH) XRHOLI
    WRITE(FH) NDAYSEC
    WRITE(FH) RDSRV
    WRITE(FH) RDSCPD
    WRITE(FH) RINVXP00
    WRITE(FH) CHECK_REF
    END SUBROUTINE SAVE_MODD_CST

    SUBROUTINE LOAD_MODD_CST(FH)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FH
    INTEGER :: CHECK
    READ(FH) CHECK
    IF(CHECK /= CHECK_REF)WRITE(*,*)__LINE__,__FILE__,"WRONG CONTROL NUMBER",CHECK

    READ(FH) XPI
    READ(FH) XDAY
    READ(FH) XSIYEA
    READ(FH) XSIDAY
    READ(FH) XKARMAN
    READ(FH) XLIGHTSPEED
    READ(FH) XPLANCK
    READ(FH) XBOLTZ
    READ(FH) XAVOGADRO
    READ(FH) XRADIUS
    READ(FH) XOMEGA
    READ(FH) XG
    READ(FH) XP00
    READ(FH) XSTEFAN
    READ(FH) XI0
    READ(FH) XMD
    READ(FH) XMV
    READ(FH) XRD
    READ(FH) XRV
    READ(FH) XEPSILO
    READ(FH) XCPD
    READ(FH) XCPV
    READ(FH) XRHOLW
    READ(FH) XCL
    READ(FH) XCI
    READ(FH) XTT
    READ(FH) XLVTT
    READ(FH) XLSTT
    READ(FH) XLMTT
    READ(FH) XESTT
    READ(FH) XALPW
    READ(FH) XBETAW
    READ(FH) XGAMW
    READ(FH) XALPI
    READ(FH) XBETAI
    READ(FH) XGAMI
    READ(FH) XCONDI
    READ(FH) XTH00
    READ(FH) XRHOLI
    READ(FH) NDAYSEC
    READ(FH) RDSRV
    READ(FH) RDSCPD
    READ(FH) RINVXP00
    READ(FH) CHECK
    IF(CHECK /= CHECK_REF)WRITE(*,*)__LINE__,__FILE__,"WRONG CONTROL NUMBER",CHECK
    END SUBROUTINE LOAD_MODD_CST
END MODULE UTIL_MODD_CST