    MODULE UTIL_MODD_CST
    INTEGER :: CHECK_REF = 123456789
    CONTAINS

    SUBROUTINE SAVE_MODD_CST(FH, CST)
    USE MODD_CST, ONLY: CST_t
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FH
    TYPE(CST_T), INTENT(IN) :: CST
    WRITE(FH) CHECK_REF

    WRITE(FH) CST%XPI
    WRITE(FH) CST%XDAY
    WRITE(FH) CST%XSIYEA
    WRITE(FH) CST%XSIDAY
    WRITE(FH) CST%XKARMAN
    WRITE(FH) CST%XLIGHTSPEED
    WRITE(FH) CST%XPLANCK
    WRITE(FH) CST%XBOLTZ
    WRITE(FH) CST%XAVOGADRO
    WRITE(FH) CST%XRADIUS
    WRITE(FH) CST%XOMEGA
    WRITE(FH) CST%XG
    WRITE(FH) CST%XP00
    WRITE(FH) CST%XSTEFAN
    WRITE(FH) CST%XI0
    WRITE(FH) CST%XMD
    WRITE(FH) CST%XMV
    WRITE(FH) CST%XRD
    WRITE(FH) CST%XRV
    WRITE(FH) CST%XEPSILO
    WRITE(FH) CST%XCPD
    WRITE(FH) CST%XCPV
    WRITE(FH) CST%XRHOLW
    WRITE(FH) CST%XCL
    WRITE(FH) CST%XCI
    WRITE(FH) CST%XTT
    WRITE(FH) CST%XLVTT
    WRITE(FH) CST%XLSTT
    WRITE(FH) CST%XLMTT
    WRITE(FH) CST%XESTT
    WRITE(FH) CST%XALPW
    WRITE(FH) CST%XBETAW
    WRITE(FH) CST%XGAMW
    WRITE(FH) CST%XALPI
    WRITE(FH) CST%XBETAI
    WRITE(FH) CST%XGAMI
    WRITE(FH) CST%XCONDI
    WRITE(FH) CST%XTH00
    WRITE(FH) CST%XRHOLI
    WRITE(FH) CST%NDAYSEC
    WRITE(FH) CST%RDSRV
    WRITE(FH) CST%RDSCPD
    WRITE(FH) CST%RINVXP00
    WRITE(FH) CHECK_REF
    END SUBROUTINE SAVE_MODD_CST

    SUBROUTINE LOAD_MODD_CST(FH, CST)
    USE MODD_CST, ONLY: CST_t
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FH
    TYPE(CST_T), INTENT(OUT) :: CST
    INTEGER :: CHECK
    READ(FH) CHECK
    IF(CHECK /= CHECK_REF)WRITE(*,*)__LINE__,__FILE__,"WRONG CONTROL NUMBER",CHECK

    READ(FH) CST%XPI
    READ(FH) CST%XDAY
    READ(FH) CST%XSIYEA
    READ(FH) CST%XSIDAY
    READ(FH) CST%XKARMAN
    READ(FH) CST%XLIGHTSPEED
    READ(FH) CST%XPLANCK
    READ(FH) CST%XBOLTZ
    READ(FH) CST%XAVOGADRO
    READ(FH) CST%XRADIUS
    READ(FH) CST%XOMEGA
    READ(FH) CST%XG
    READ(FH) CST%XP00
    READ(FH) CST%XSTEFAN
    READ(FH) CST%XI0
    READ(FH) CST%XMD
    READ(FH) CST%XMV
    READ(FH) CST%XRD
    READ(FH) CST%XRV
    READ(FH) CST%XEPSILO
    READ(FH) CST%XCPD
    READ(FH) CST%XCPV
    READ(FH) CST%XRHOLW
    READ(FH) CST%XCL
    READ(FH) CST%XCI
    READ(FH) CST%XTT
    READ(FH) CST%XLVTT
    READ(FH) CST%XLSTT
    READ(FH) CST%XLMTT
    READ(FH) CST%XESTT
    READ(FH) CST%XALPW
    READ(FH) CST%XBETAW
    READ(FH) CST%XGAMW
    READ(FH) CST%XALPI
    READ(FH) CST%XBETAI
    READ(FH) CST%XGAMI
    READ(FH) CST%XCONDI
    READ(FH) CST%XTH00
    READ(FH) CST%XRHOLI
    READ(FH) CST%NDAYSEC
    READ(FH) CST%RDSRV
    READ(FH) CST%RDSCPD
    READ(FH) CST%RINVXP00
    READ(FH) CHECK
    IF(CHECK /= CHECK_REF)WRITE(*,*)__LINE__,__FILE__,"WRONG CONTROL NUMBER",CHECK
    END SUBROUTINE LOAD_MODD_CST
END MODULE UTIL_MODD_CST
