!OPTIONS XOPT(NOEVAL)
!-----------------------------------------------------------------
SUBROUTINE WRAP_ACVPPKF(NSTEPMAX, NPROMA, LAST_BLK_NPROMA, NFLEV, NBLKS)

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMCST  , ONLY :  TCST
USE UTIL_TCST_MOD
USE UTIL_MODEL_PHYSICS_MF_TYPE_MOD
USE YOMLSFORC, ONLY :LMUSCLFA, NMUSCLFA
USE UTIL_MODD_CONVPAR_SHAL, ONLY : LOAD_MODD_CONVPAR_SHAL
USE MODD_NSV, ONLY : NSV_LGBEG, NSV_LGEND
USE UTIL_MODD_CST, ONLY: LOAD_MODD_CST
use yomdbg
!-----------------------------------------------------------------

IMPLICIT NONE

INTEGER, INTENT(IN) :: NSTEPMAX, NPROMA, LAST_BLK_NPROMA, NFLEV, NBLKS

!TYPE (TCST), INTENT (IN) :: YDCST
!TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KIDIA
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KFDIA
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KLON
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KTDIA
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KLEV
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PAPRSF (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PAPHIF (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PDELP  (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PR     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PT     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PQ     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PQL    (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PQI    (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PU     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PV     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PVERVEL(KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PCP    (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PTKE   (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PDIFCQ (KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PDIFCS (KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PFCCQL (KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PFCCQN (KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PPRODTH(KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PQCPP  (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PNEBPP (KLON,KLEV)
!INTEGER(KIND=JPIM) ,INTENT(OUT)   :: KNLAB  (KLON,KLEV)
!INTEGER(KIND=JPIM) ,INTENT(OUT)   :: KNND   (KLON)

TYPE (TCST) :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
INTEGER(KIND=JPIM) :: KIDIA
INTEGER(KIND=JPIM) :: KFDIA
INTEGER(KIND=JPIM) :: KLON
INTEGER(KIND=JPIM) :: KTDIA
INTEGER(KIND=JPIM) :: KLEV
REAL(KIND=JPRB), ALLOCATABLE    :: PAPRSF (:,:,:),PAPRSF_buf (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PAPHIF (:,:,:),PAPHIF_buf (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PDELP  (:,:,:),PDELP_buf  (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PR     (:,:,:),PR_buf     (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PT     (:,:,:),PT_buf     (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PQ     (:,:,:),PQ_buf     (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PQL    (:,:,:),PQL_buf    (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PQI    (:,:,:),PQI_buf    (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PU     (:,:,:),PU_buf     (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PV     (:,:,:),PV_buf     (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PVERVEL(:,:,:),PVERVEL_buf(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PCP    (:,:,:),PCP_buf    (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PTKE   (:,:,:),PTKE_buf   (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PDIFCQ (:,:,:),PDIFCQ_buf (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PDIFCS (:,:,:),PDIFCS_buf (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PFCCQL (:,:,:),PFCCQL_buf (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PFCCQN (:,:,:),PFCCQN_buf (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PPRODTH(:,:,:),PPRODTH_buf(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PQCPP  (:,:,:),PQCPP_buf  (:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE    :: PNEBPP (:,:,:),PNEBPP_buf (:,:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE :: KNLAB  (:,:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: KNND   (:,:)  

REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PDIFCQ (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PDIFCS (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PFCCQL (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PFCCQN (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PPRODTH(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PQCPP  (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PNEBPP (:,:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ORI_KNLAB  (:,:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ORI_KNND   (:,:)

INTEGER :: FH_IN, FH_OUT, CHECK, I, J, K, NSTEP
INTEGER :: BLK_SIZE, MAX_BLK_SIZE
INTEGER, PARAMETER :: CHECK_VAL = 123456789

#include "acvppkf.intfb.h"

KLON=NPROMA
KLEV=NFLEV
MAX_BLK_SIZE=MAX(NPROMA,LAST_BLK_NPROMA)

ALLOCATE(PAPRSF (MAX_BLK_SIZE,KLEV,NBLKS),PAPRSF_BUF (1784,KLEV,NSTEPMAX))
ALLOCATE(PAPHIF (MAX_BLK_SIZE,KLEV,NBLKS),PAPHIF_BUF (1784,KLEV,NSTEPMAX))
ALLOCATE(PDELP  (MAX_BLK_SIZE,KLEV,NBLKS),PDELP_BUF  (1784,KLEV,NSTEPMAX))
ALLOCATE(PR     (MAX_BLK_SIZE,KLEV,NBLKS),PR_BUF     (1784,KLEV,NSTEPMAX))
ALLOCATE(PT     (MAX_BLK_SIZE,KLEV,NBLKS),PT_BUF     (1784,KLEV,NSTEPMAX))
ALLOCATE(PQ     (MAX_BLK_SIZE,KLEV,NBLKS),PQ_BUF     (1784,KLEV,NSTEPMAX))
ALLOCATE(PQL    (MAX_BLK_SIZE,KLEV,NBLKS),PQL_BUF    (1784,KLEV,NSTEPMAX))
ALLOCATE(PQI    (MAX_BLK_SIZE,KLEV,NBLKS),PQI_BUF    (1784,KLEV,NSTEPMAX))
ALLOCATE(PU     (MAX_BLK_SIZE,KLEV,NBLKS),PU_BUF     (1784,KLEV,NSTEPMAX))
ALLOCATE(PV     (MAX_BLK_SIZE,KLEV,NBLKS),PV_BUF     (1784,KLEV,NSTEPMAX))
ALLOCATE(PVERVEL(MAX_BLK_SIZE,KLEV,NBLKS),PVERVEL_BUF(1784,KLEV,NSTEPMAX))
ALLOCATE(PCP    (MAX_BLK_SIZE,KLEV,NBLKS),PCP_BUF    (1784,KLEV,NSTEPMAX))
ALLOCATE(PTKE   (MAX_BLK_SIZE,KLEV,NBLKS),PTKE_BUF   (1784,KLEV,NSTEPMAX))
ALLOCATE(PDIFCQ (MAX_BLK_SIZE,0:KLEV,NBLKS),PDIFCQ_BUF (1784,0:KLEV,NSTEPMAX))
ALLOCATE(PDIFCS (MAX_BLK_SIZE,0:KLEV,NBLKS),PDIFCS_BUF (1784,0:KLEV,NSTEPMAX))
ALLOCATE(PFCCQL (MAX_BLK_SIZE,0:KLEV,NBLKS),PFCCQL_BUF (1784,0:KLEV,NSTEPMAX))
ALLOCATE(PFCCQN (MAX_BLK_SIZE,0:KLEV,NBLKS),PFCCQN_BUF (1784,0:KLEV,NSTEPMAX))
ALLOCATE(PPRODTH(MAX_BLK_SIZE,0:KLEV,NBLKS),PPRODTH_BUF(1784,0:KLEV,NSTEPMAX))
ALLOCATE(PQCPP  (MAX_BLK_SIZE,KLEV,NBLKS),PQCPP_BUF  (1784,KLEV,NSTEPMAX))
ALLOCATE(PNEBPP (MAX_BLK_SIZE,KLEV,NBLKS),PNEBPP_BUF (1784,KLEV,NSTEPMAX))
ALLOCATE(KNLAB  (MAX_BLK_SIZE,KLEV,NBLKS))
ALLOCATE(KNND   (MAX_BLK_SIZE,NBLKS))

ALLOCATE(ORI_PDIFCQ (1784,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PDIFCS (1784,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PFCCQL (1784,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PFCCQN (1784,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PPRODTH(1784,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PQCPP  (1784,KLEV,NSTEPMAX))
ALLOCATE(ORI_PNEBPP (1784,KLEV,NSTEPMAX))
ALLOCATE(ORI_KNLAB  (1784,KLEV,NSTEPMAX))
ALLOCATE(ORI_KNND   (1784,NSTEPMAX))

OPEN (NEWUNIT=FH_IN, FILE="DATA/ACVPPKF.IN.DAT", ACTION="READ", ACCESS="STREAM")
OPEN (NEWUNIT=FH_OUT, FILE="DATA/ACVPPKF.OUT.DAT", ACTION="READ", ACCESS="STREAM")

DO NSTEP=1,NSTEPMAX
  READ(FH_IN)CHECK
  IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
  READ(FH_IN)LMUSCLFA
  READ(FH_IN)NMUSCLFA
  READ(FH_IN) NSV_LGBEG
  READ(FH_IN) NSV_LGEND
  CALL LOAD (FH_IN, YDCST)
  CALL LOAD (FH_IN, YDML_PHY_MF)
  CALL LOAD_MODD_CONVPAR_SHAL(FH_IN)
  CALL LOAD_MODD_CST(FH_IN)
  READ(FH_IN) KIDIA
  READ(FH_IN) KFDIA
  READ(FH_IN) KLON
  READ(FH_IN) KTDIA
  READ(FH_IN) KLEV
  READ(FH_IN) PAPRSF_BUF(:,:,NSTEP)
  READ(FH_IN) PAPHIF_BUF(:,:,NSTEP)
  READ(FH_IN) PDELP_BUF(:,:,NSTEP)
  READ(FH_IN) PR_BUF(:,:,NSTEP)
  READ(FH_IN) PT_BUF(:,:,NSTEP)
  READ(FH_IN) PQ_BUF(:,:,NSTEP)
  READ(FH_IN) PQL_BUF(:,:,NSTEP)
  READ(FH_IN) PQI_BUF(:,:,NSTEP)
  READ(FH_IN) PU_BUF(:,:,NSTEP)
  READ(FH_IN) PV_BUF(:,:,NSTEP)
  READ(FH_IN) PVERVEL_BUF(:,:,NSTEP)
  READ(FH_IN) PCP_BUF(:,:,NSTEP)
  READ(FH_IN) PTKE_BUF(:,:,NSTEP)
  READ(FH_IN) PDIFCQ_BUF(:,:,NSTEP)
  READ(FH_IN) PDIFCS_BUF(:,:,NSTEP)
  READ(FH_IN) PFCCQL_BUF(:,:,NSTEP)
  READ(FH_IN) PFCCQN_BUF(:,:,NSTEP)
  READ(FH_IN) PPRODTH_BUF(:,:,NSTEP)
  READ(FH_IN) PQCPP_BUF(:,:,NSTEP)
  READ(FH_IN) PNEBPP_BUF(:,:,NSTEP)
  READ(FH_IN)CHECK
  IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK

  READ(FH_OUT)CHECK
  IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
  READ(FH_OUT)ORI_PDIFCQ(:,:,NSTEP)
  READ(FH_OUT)ORI_PDIFCS(:,:,NSTEP)
  READ(FH_OUT)ORI_PFCCQL(:,:,NSTEP)
  READ(FH_OUT)ORI_PFCCQN(:,:,NSTEP)
  READ(FH_OUT)ORI_PPRODTH(:,:,NSTEP)
  READ(FH_OUT)ORI_PQCPP(:,:,NSTEP)
  READ(FH_OUT)ORI_PNEBPP(:,:,NSTEP)
  READ(FH_OUT)ORI_KNLAB(:,:,NSTEP)
  READ(FH_OUT)ORI_KNND(:,NSTEP)
  READ(FH_OUT)CHECK
  IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
  
ENDDO
CLOSE(FH_IN)
CLOSE(FH_OUT)


DO NSTEP=1,NSTEPMAX
  WRITE(*,*)"NSTEP:",NSTEP

  DO K=1,NBLKS
    IF(K==NBLKS)THEN
            BLK_SIZE = LAST_BLK_NPROMA
    ELSE
            BLK_SIZE = NPROMA
    ENDIF
    DO J=0,KLEV
      DO I=1,BLK_SIZE
        IF (J>0)THEN
          PAPRSF (I,J,K)=PAPRSF_BUF (I+(K-1)*NPROMA,J,NSTEP)
          PAPHIF (I,J,K)=PAPHIF_BUF (I+(K-1)*NPROMA,J,NSTEP)
          PDELP  (I,J,K)=PDELP_BUF  (I+(K-1)*NPROMA,J,NSTEP)
          PR     (I,J,K)=PR_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PT     (I,J,K)=PT_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PQ     (I,J,K)=PQ_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PQL    (I,J,K)=PQL_BUF    (I+(K-1)*NPROMA,J,NSTEP)
          PQI    (I,J,K)=PQI_BUF    (I+(K-1)*NPROMA,J,NSTEP)
          PU     (I,J,K)=PU_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PV     (I,J,K)=PV_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PVERVEL(I,J,K)=PVERVEL_BUF(I+(K-1)*NPROMA,J,NSTEP)
          PCP    (I,J,K)=PCP_BUF    (I+(K-1)*NPROMA,J,NSTEP)
          PTKE   (I,J,K)=PTKE_BUF   (I+(K-1)*NPROMA,J,NSTEP)
          PQCPP  (I,J,K)=PQCPP_BUF  (I+(K-1)*NPROMA,J,NSTEP)
          PNEBPP (I,J,K)=PNEBPP_BUF (I+(K-1)*NPROMA,J,NSTEP)
        ENDIF
        PDIFCQ (I,J,K)=PDIFCQ_BUF (I+(K-1)*NPROMA,J,NSTEP)
        PDIFCS (I,J,K)=PDIFCS_BUF (I+(K-1)*NPROMA,J,NSTEP)
        PFCCQL (I,J,K)=PFCCQL_BUF (I+(K-1)*NPROMA,J,NSTEP)
        PFCCQN (I,J,K)=PFCCQN_BUF (I+(K-1)*NPROMA,J,NSTEP)
        PPRODTH(I,J,K)=PPRODTH_BUF(I+(K-1)*NPROMA,J,NSTEP)
      ENDDO
    ENDDO
  ENDDO

  DO K=1,NBLKS
    IF(K==NBLKS)THEN
            BLK_SIZE = LAST_BLK_NPROMA
    ELSE
            BLK_SIZE = NPROMA
    ENDIF
    CALL ACVPPKF(YDCST,YDML_PHY_MF, KIDIA, BLK_SIZE, MAX_BLK_SIZE, KTDIA, KLEV,  &
    & PAPRSF(:,:,K), PAPHIF(:,:,K), PDELP(:,:,K),  &
    & PR(:,:,K), PT(:,:,K), PQ(:,:,K), PQL(:,:,K), PQI(:,:,K), PU(:,:,K),&
    & PV(:,:,K), PVERVEL(:,:,K), PCP(:,:,K), PTKE(:,:,K), &
    & PDIFCQ(:,:,K), PDIFCS(:,:,K), PFCCQL(:,:,K), PFCCQN(:,:,K), PPRODTH(:,:,K), &
    & KNLAB(:,:,K), PQCPP(:,:,K), PNEBPP(:,:,K),&
    & KNND(:,K))
  ENDDO

  DO K=1,NBLKS
    IF(K==NBLKS)THEN
            BLK_SIZE = LAST_BLK_NPROMA
    ELSE
            BLK_SIZE = NPROMA
    ENDIF
    DO J=0,KLEV
      DO I=1,BLK_SIZE
        IF(ORI_PDIFCQ(I+(K-1)*NPROMA,J,NSTEP) /= PDIFCQ(I,J,K))WRITE(*,*)"ERROR ORI_PDIFCQ",ORI_PDIFCQ(I+(K-1)*BLK_SIZE,J,NSTEP),PDIFCQ(I,J,K)
        IF(ORI_PDIFCS(I+(K-1)*NPROMA,J,NSTEP) /= PDIFCS(I,J,K))WRITE(*,*)"ERROR ORI_PDIFCS"
        IF(ORI_PFCCQL(I+(K-1)*NPROMA,J,NSTEP) /= PFCCQL(I,J,K))WRITE(*,*)"ERROR ORI_PFCCQL"
        IF(ORI_PFCCQN(I+(K-1)*NPROMA,J,NSTEP) /= PFCCQN(I,J,K))WRITE(*,*)"ERROR ORI_PFCCQN"
        IF(ORI_PPRODTH(I+(K-1)*NPROMA,J,NSTEP) /= PPRODTH(I,J,K))WRITE(*,*)"ERROR ORI_PPRODTH"
        IF(J>0)THEN
          IF(ORI_PQCPP(I+(K-1)*NPROMA,J,NSTEP) /= PQCPP(I,J,K))WRITE(*,*)"ERROR ORI_PQCPP"
          IF(ORI_PNEBPP(I+(K-1)*NPROMA,J,NSTEP) /= PNEBPP(I,J,K))WRITE(*,*)"ERROR ORI_PNEBPP"
          IF(ORI_KNLAB(I+(K-1)*NPROMA,J,NSTEP) /= KNLAB(I,J,K))WRITE(*,*)"ERROR ORI_KNLAB"
          IF(ORI_KNND(I+(K-1)*NPROMA,NSTEP) /= KNND(I,K))WRITE(*,*)"ERROR ORI_KNND"
        ENDIF
      ENDDO
    ENDDO
  ENDDO
ENDDO
END SUBROUTINE WRAP_ACVPPKF
