!OPTIONS XOPT(NOEVAL)
!-----------------------------------------------------------------
SUBROUTINE WRAP_ACVPPKF(NSTEPMAX, NPROMA, LAST_BLK_NPROMA, NFLEV, NBLKS)

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMCST  , ONLY :  TCST
USE YOMCT3               , ONLY : NSTEP
USE UTIL_TCST_MOD
USE UTIL_MODEL_PHYSICS_MF_TYPE_MOD
USE YOMLSFORC, ONLY :LMUSCLFA, NMUSCLFA
USE UTIL_MODD_CONVPAR_SHAL, ONLY : LOAD_MODD_CONVPAR_SHAL
!-----------------------------------------------------------------

IMPLICIT NONE

INTEGER, INTENT(IN) :: NSTEPMAX, NPROMA, LAST_BLK_NPROMA, NFLEV, NBLKS

!TYPE (TCST), INTENT (IN) :: YDCST
!TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KIDIA
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KFDIA
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KLON
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KTDIA
!INTEGER(KIND=JPIM) ,INTENT(IN)    :: KLEV
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PAPRSF (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PAPHIF (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PDELP  (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PR     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PT     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PQ     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PQL    (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PQI    (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PU     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PV     (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PVERVEL(KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PCP    (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(IN)    :: PTKE   (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PDIFCQ (KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PDIFCS (KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PFCCQL (KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PFCCQN (KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PPRODTH(KLON,0:KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PQCPP  (KLON,KLEV)
!REAL(KIND=JPRB)    ,INTENT(INOUT) :: PNEBPP (KLON,KLEV)
!INTEGER(KIND=JPIM) ,INTENT(OUT)   :: KNLAB  (KLON,KLEV)
!INTEGER(KIND=JPIM) ,INTENT(OUT)   :: KNND   (KLON)

TYPE (TCST) :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
INTEGER(KIND=JPIM) :: KIDIA
INTEGER(KIND=JPIM) :: KFDIA
INTEGER(KIND=JPIM) :: KLON
INTEGER(KIND=JPIM) :: KTDIA
INTEGER(KIND=JPIM) :: KLEV
REAL(KIND=JPRB), ALLOCATABLE    :: PAPRSF (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PAPHIF (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PDELP  (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PR     (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PT     (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PQ     (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PQL    (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PQI    (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PU     (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PV     (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PVERVEL(:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PCP    (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PTKE   (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PDIFCQ (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PDIFCS (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PFCCQL (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PFCCQN (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PPRODTH(:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PQCPP  (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PNEBPP (:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: KNLAB  (:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: KNND   (:)

REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PDIFCQ (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PDIFCS (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PFCCQL (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PFCCQN (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PPRODTH(:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PQCPP  (:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PNEBPP (:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ORI_KNLAB  (:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ORI_KNND   (:)

INTEGER :: FH, CHECK, I, J
INTEGER, PARAMETER :: CHECK_VAL = 123456789

#include "acvppkf.intfb.h"

KLON=NPROMA
KLEV=NFLEV

ALLOCATE(PAPRSF (KLON,KLEV))
ALLOCATE(PAPHIF (KLON,KLEV))
ALLOCATE(PDELP  (KLON,KLEV))
ALLOCATE(PR     (KLON,KLEV))
ALLOCATE(PT     (KLON,KLEV))
ALLOCATE(PQ     (KLON,KLEV))
ALLOCATE(PQL    (KLON,KLEV))
ALLOCATE(PQI    (KLON,KLEV))
ALLOCATE(PU     (KLON,KLEV))
ALLOCATE(PV     (KLON,KLEV))
ALLOCATE(PVERVEL(KLON,KLEV))
ALLOCATE(PCP    (KLON,KLEV))
ALLOCATE(PTKE   (KLON,KLEV))
ALLOCATE(PDIFCQ (KLON,0:KLEV))
ALLOCATE(PDIFCS (KLON,0:KLEV))
ALLOCATE(PFCCQL (KLON,0:KLEV))
ALLOCATE(PFCCQN (KLON,0:KLEV))
ALLOCATE(PPRODTH(KLON,0:KLEV))
ALLOCATE(PQCPP  (KLON,KLEV))
ALLOCATE(PNEBPP (KLON,KLEV))
ALLOCATE(KNLAB  (KLON,KLEV))
ALLOCATE(KNND   (KLON))

ALLOCATE(ORI_PDIFCQ (KLON,0:KLEV))
ALLOCATE(ORI_PDIFCS (KLON,0:KLEV))
ALLOCATE(ORI_PFCCQL (KLON,0:KLEV))
ALLOCATE(ORI_PFCCQN (KLON,0:KLEV))
ALLOCATE(ORI_PPRODTH(KLON,0:KLEV))
ALLOCATE(ORI_PQCPP  (KLON,KLEV))
ALLOCATE(ORI_PNEBPP (KLON,KLEV))
ALLOCATE(ORI_KNLAB  (KLON,KLEV))
ALLOCATE(ORI_KNND   (KLON))

OPEN (NEWUNIT=FH, FILE="DATA/ACVPPKF.IN.DAT", ACTION="READ", ACCESS="STREAM")
READ(FH)CHECK
IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
READ(FH)LMUSCLFA
READ(FH)NMUSCLFA
CALL LOAD (FH, YDCST)
CALL LOAD (FH, YDML_PHY_MF)
CALL LOAD_MODD_CONVPAR_SHAL(FH)
READ(FH) KIDIA
READ(FH) KFDIA
READ(FH) KLON
READ(FH) KTDIA
READ(FH) KLEV
READ(FH) PAPRSF
READ(FH) PAPHIF
READ(FH) PDELP
READ(FH) PR
READ(FH) PT
READ(FH) PQ
READ(FH) PQL
READ(FH) PQI
READ(FH) PU
READ(FH) PV
READ(FH) PVERVEL
READ(FH) PCP
READ(FH) PTKE
READ(FH) PDIFCQ
READ(FH) PDIFCS
READ(FH) PFCCQL
READ(FH) PFCCQN
READ(FH) PPRODTH
READ(FH) PQCPP
READ(FH) PNEBPP
READ(FH)CHECK
IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
CLOSE(FH)

CALL ACVPPKF(YDCST,YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV,  &
& PAPRSF, PAPHIF, PDELP,  &
& PR, PT, PQ, PQL, PQI, PU,                 &
& PV, PVERVEL, PCP, PTKE, &
& PDIFCQ, PDIFCS, PFCCQL, PFCCQN, PPRODTH, KNLAB, PQCPP, PNEBPP,                       &
& KNND)

OPEN (NEWUNIT=FH, FILE="DATA/ACVPPKF.OUT.DAT", ACTION="READ", ACCESS="STREAM")
READ(FH)CHECK
IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
READ(FH)ORI_PDIFCQ
READ(FH)ORI_PDIFCS
READ(FH)ORI_PFCCQL
READ(FH)ORI_PFCCQN
READ(FH)ORI_PPRODTH
READ(FH)ORI_PQCPP
READ(FH)ORI_PNEBPP
READ(FH)ORI_KNLAB
READ(FH)ORI_KNND
READ(FH)CHECK
IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
CLOSE(FH)

DO I=0,KLEV
  DO J=1,KLON
    IF(ORI_PDIFCQ(J,I) /= PDIFCQ(J,I))WRITE(*,*)"ERROR IN ORI_PDIFCQ",ORI_PDIFCQ(J,I),PDIFCQ(J,I)
    IF(ORI_PDIFCS(J,I) /= PDIFCS(J,I))WRITE(*,*)"ERROR IN ORI_PDIFCS"
    IF(ORI_PFCCQL(J,I) /= PFCCQL(J,I))WRITE(*,*)"ERROR IN ORI_PFCCQL"
    IF(ORI_PFCCQN(J,I) /= PFCCQN(J,I))WRITE(*,*)"ERROR IN ORI_PFCCQN"
    IF(ORI_PPRODTH(J,I) /= PPRODTH(J,I))WRITE(*,*)"ERROR IN ORI_PPRODTH"
    IF(I>0)THEN
      IF(ORI_PQCPP(J,I) /= PQCPP(J,I))WRITE(*,*)"ERROR IN ORI_PQCPP"
      IF(ORI_PNEBPP(J,I) /= PNEBPP(J,I))WRITE(*,*)"ERROR IN ORI_PNEBPP"
      IF(ORI_KNLAB(J,I) /= KNLAB(J,I))WRITE(*,*)"ERROR IN ORI_KNLAB"
      IF(ORI_KNND(J) /= KNND(J))WRITE(*,*)"ERROR IN ORI_KNND"
    ENDIF
  ENDDO
ENDDO

END SUBROUTINE WRAP_ACVPPKF
