!OPTIONS XOPT(NOEVAL)
!-----------------------------------------------------------------
SUBROUTINE WRAP_ACVPPKF(DATA_PATH, NSTEPMAX, NPROMA, LAST_BLK_NPROMA,&
                        KLEV, NBLKS, GRID_SIZE)

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMCST  , ONLY :  TCST
USE UTIL_TCST_MOD
USE UTIL_MODEL_PHYSICS_MF_TYPE_MOD
USE YOMLSFORC, ONLY :LMUSCLFA, NMUSCLFA
USE UTIL_MODD_CONVPAR_SHAL, ONLY : LOAD_MODD_CONVPAR_SHAL
USE MODD_NSV, ONLY : NSV_LGBEG, NSV_LGEND
USE UTIL_MODD_CST, ONLY: LOAD_MODD_CST
USE MODD_CST, ONLY: CST_T
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
USE YOMDBG
USE YOMHOOK
!-----------------------------------------------------------------

IMPLICIT NONE

INTEGER, INTENT(IN) :: NSTEPMAX, NPROMA, LAST_BLK_NPROMA, KLEV, NBLKS, &
GRID_SIZE
CHARACTER(LEN=1024) :: DATA_PATH

TYPE (TCST) :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
INTEGER(KIND=JPIM) :: KIDIA
INTEGER(KIND=JPIM) :: KTDIA
REAL(KIND=JPRB), ALLOCATABLE    :: PAPRSF (:,:,:,:),PAPRSF_BUF (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PAPHIF (:,:,:,:),PAPHIF_BUF (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PDELP  (:,:,:,:),PDELP_BUF  (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PR     (:,:,:,:),PR_BUF     (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PT     (:,:,:,:),PT_BUF     (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PQ     (:,:,:,:),PQ_BUF     (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PQL    (:,:,:,:),PQL_BUF    (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PQI    (:,:,:,:),PQI_BUF    (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PU     (:,:,:,:),PU_BUF     (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PV     (:,:,:,:),PV_BUF     (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PVERVEL(:,:,:,:),PVERVEL_BUF(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PCP    (:,:,:,:),PCP_BUF    (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PTKE   (:,:,:,:),PTKE_BUF   (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PDIFCQ (:,:,:,:),PDIFCQ_BUF (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PDIFCS (:,:,:,:),PDIFCS_BUF (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PFCCQL (:,:,:,:),PFCCQL_BUF (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PFCCQN (:,:,:,:),PFCCQN_BUF (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PPRODTH(:,:,:,:),PPRODTH_BUF(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PQCPP  (:,:,:,:),PQCPP_BUF  (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: PNEBPP (:,:,:,:),PNEBPP_BUF (:,:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: KNLAB  (:,:,:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: KNND   (:,:,:)

REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PDIFCQ (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PDIFCS (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PFCCQL (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PFCCQN (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PPRODTH(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PQCPP  (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE    :: ORI_PNEBPP (:,:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ORI_KNLAB  (:,:,:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ORI_KNND   (:,:)

INTEGER :: FH_IN, FH_OUT, FH_CONST, CHECK, I, J, K, NSTEP
INTEGER :: BLK_SIZE, MAX_BLK_SIZE, IGNORE_IT
INTEGER, PARAMETER :: CHECK_VAL = 123456789
REAL(KIND=JPRB) :: ZHOOK_HANDLE
TYPE(CST_T) :: CST
TYPE(DIMPHYEX_t) :: D

#include "acvppkf.intfb.h"

IF (LHOOK) CALL DR_HOOK('WRAP_ACVPPKF',0,ZHOOK_HANDLE)
MAX_BLK_SIZE=MAX(NPROMA,LAST_BLK_NPROMA)

ALLOCATE(PAPRSF (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PAPRSF_BUF (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PAPHIF (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PAPHIF_BUF (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PDELP  (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PDELP_BUF  (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PR     (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PR_BUF     (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PT     (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PT_BUF     (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PQ     (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PQ_BUF     (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PQL    (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PQL_BUF    (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PQI    (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PQI_BUF    (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PU     (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PU_BUF     (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PV     (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PV_BUF     (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PVERVEL(MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PVERVEL_BUF(GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PCP    (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PCP_BUF    (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PTKE   (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PTKE_BUF   (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PDIFCQ (MAX_BLK_SIZE,0:KLEV,NBLKS,NSTEPMAX),PDIFCQ_BUF (GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(PDIFCS (MAX_BLK_SIZE,0:KLEV,NBLKS,NSTEPMAX),PDIFCS_BUF (GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(PFCCQL (MAX_BLK_SIZE,0:KLEV,NBLKS,NSTEPMAX),PFCCQL_BUF (GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(PFCCQN (MAX_BLK_SIZE,0:KLEV,NBLKS,NSTEPMAX),PFCCQN_BUF (GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(PPRODTH(MAX_BLK_SIZE,0:KLEV,NBLKS,NSTEPMAX),PPRODTH_BUF(GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(PQCPP  (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PQCPP_BUF  (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(PNEBPP (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX),PNEBPP_BUF (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(KNLAB  (MAX_BLK_SIZE,KLEV,NBLKS,NSTEPMAX))
ALLOCATE(KNND   (MAX_BLK_SIZE,NBLKS,NSTEPMAX))

ALLOCATE(ORI_PDIFCQ (GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PDIFCS (GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PFCCQL (GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PFCCQN (GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PPRODTH(GRID_SIZE,0:KLEV,NSTEPMAX))
ALLOCATE(ORI_PQCPP  (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(ORI_PNEBPP (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(ORI_KNLAB  (GRID_SIZE,KLEV,NSTEPMAX))
ALLOCATE(ORI_KNND   (GRID_SIZE,NSTEPMAX))

!Read original inputs/outputs
OPEN (NEWUNIT=FH_IN, FILE=TRIM(DATA_PATH)//"/ACVPPKF.IN.DAT", ACTION="READ", ACCESS="STREAM")
OPEN (NEWUNIT=FH_OUT, FILE=TRIM(DATA_PATH)//"/ACVPPKF.OUT.DAT", ACTION="READ", ACCESS="STREAM")
OPEN (NEWUNIT=FH_CONST, FILE=TRIM(DATA_PATH)//"/ACVPPKF.CONST.DAT", ACTION="READ", ACCESS="STREAM")

READ(FH_CONST)CHECK
IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
READ(FH_CONST) IGNORE_IT
READ(FH_CONST) IGNORE_IT
READ(FH_CONST) LMUSCLFA
READ(FH_CONST) NMUSCLFA
READ(FH_CONST) NSV_LGBEG
READ(FH_CONST) NSV_LGEND
READ(FH_CONST) KIDIA
READ(FH_CONST) KTDIA
CALL LOAD (FH_CONST, YDCST)
CALL LOAD (FH_CONST, YDML_PHY_MF)
CALL LOAD_MODD_CONVPAR_SHAL(FH_CONST)
CALL LOAD_MODD_CST(FH_CONST, CST)
READ(FH_CONST)CHECK
IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
CLOSE(FH_CONST) 


DO NSTEP=1,NSTEPMAX
  READ(FH_IN)CHECK
  IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
  READ(FH_IN) PAPRSF_BUF(:,:,NSTEP)
  READ(FH_IN) PAPHIF_BUF(:,:,NSTEP)
  READ(FH_IN) PDELP_BUF(:,:,NSTEP)
  READ(FH_IN) PR_BUF(:,:,NSTEP)
  READ(FH_IN) PT_BUF(:,:,NSTEP)
  READ(FH_IN) PQ_BUF(:,:,NSTEP)
  READ(FH_IN) PQL_BUF(:,:,NSTEP)
  READ(FH_IN) PQI_BUF(:,:,NSTEP)
  READ(FH_IN) PU_BUF(:,:,NSTEP)
  READ(FH_IN) PV_BUF(:,:,NSTEP)
  READ(FH_IN) PVERVEL_BUF(:,:,NSTEP)
  READ(FH_IN) PCP_BUF(:,:,NSTEP)
  READ(FH_IN) PTKE_BUF(:,:,NSTEP)
  READ(FH_IN) PDIFCQ_BUF(:,:,NSTEP)
  READ(FH_IN) PDIFCS_BUF(:,:,NSTEP)
  READ(FH_IN) PFCCQL_BUF(:,:,NSTEP)
  READ(FH_IN) PFCCQN_BUF(:,:,NSTEP)
  READ(FH_IN) PPRODTH_BUF(:,:,NSTEP)
  READ(FH_IN) PQCPP_BUF(:,:,NSTEP)
  READ(FH_IN) PNEBPP_BUF(:,:,NSTEP)
  READ(FH_IN)CHECK
  IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK

  READ(FH_OUT)CHECK
  IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
  READ(FH_OUT)ORI_PDIFCQ(:,:,NSTEP)
  READ(FH_OUT)ORI_PDIFCS(:,:,NSTEP)
  READ(FH_OUT)ORI_PFCCQL(:,:,NSTEP)
  READ(FH_OUT)ORI_PFCCQN(:,:,NSTEP)
  READ(FH_OUT)ORI_PPRODTH(:,:,NSTEP)
  READ(FH_OUT)ORI_PQCPP(:,:,NSTEP)
  READ(FH_OUT)ORI_PNEBPP(:,:,NSTEP)
  READ(FH_OUT)ORI_KNLAB(:,:,NSTEP)
  READ(FH_OUT)ORI_KNND(:,NSTEP)
  READ(FH_OUT)CHECK
  IF(CHECK /= CHECK_VAL)WRITE(*,*)__LINE__,"WRONG CONTROL NUMBER",CHECK
ENDDO
CLOSE(FH_IN)
CLOSE(FH_OUT)
CLOSE(FH_CONST)

!Convert to blocks
DO NSTEP=1,NSTEPMAX
  DO K=1,NBLKS
    IF(K==NBLKS)THEN
      BLK_SIZE = LAST_BLK_NPROMA
    ELSE
      BLK_SIZE = NPROMA
    ENDIF
    DO J=0,KLEV
      DO I=1,BLK_SIZE
        IF (J>0)THEN
          PAPRSF (I,J,K,NSTEP)=PAPRSF_BUF (I+(K-1)*NPROMA,J,NSTEP)
          PAPHIF (I,J,K,NSTEP)=PAPHIF_BUF (I+(K-1)*NPROMA,J,NSTEP)
          PDELP  (I,J,K,NSTEP)=PDELP_BUF  (I+(K-1)*NPROMA,J,NSTEP)
          PR     (I,J,K,NSTEP)=PR_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PT     (I,J,K,NSTEP)=PT_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PQ     (I,J,K,NSTEP)=PQ_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PQL    (I,J,K,NSTEP)=PQL_BUF    (I+(K-1)*NPROMA,J,NSTEP)
          PQI    (I,J,K,NSTEP)=PQI_BUF    (I+(K-1)*NPROMA,J,NSTEP)
          PU     (I,J,K,NSTEP)=PU_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PV     (I,J,K,NSTEP)=PV_BUF     (I+(K-1)*NPROMA,J,NSTEP)
          PVERVEL(I,J,K,NSTEP)=PVERVEL_BUF(I+(K-1)*NPROMA,J,NSTEP)
          PCP    (I,J,K,NSTEP)=PCP_BUF    (I+(K-1)*NPROMA,J,NSTEP)
          PTKE   (I,J,K,NSTEP)=PTKE_BUF   (I+(K-1)*NPROMA,J,NSTEP)
          PQCPP  (I,J,K,NSTEP)=PQCPP_BUF  (I+(K-1)*NPROMA,J,NSTEP)
          PNEBPP (I,J,K,NSTEP)=PNEBPP_BUF (I+(K-1)*NPROMA,J,NSTEP)
        ENDIF
        PDIFCQ (I,J,K,NSTEP)=PDIFCQ_BUF (I+(K-1)*NPROMA,J,NSTEP)
        PDIFCS (I,J,K,NSTEP)=PDIFCS_BUF (I+(K-1)*NPROMA,J,NSTEP)
        PFCCQL (I,J,K,NSTEP)=PFCCQL_BUF (I+(K-1)*NPROMA,J,NSTEP)
        PFCCQN (I,J,K,NSTEP)=PFCCQN_BUF (I+(K-1)*NPROMA,J,NSTEP)
        PPRODTH(I,J,K,NSTEP)=PPRODTH_BUF(I+(K-1)*NPROMA,J,NSTEP)
      ENDDO
    ENDDO
  ENDDO
ENDDO
DEALLOCATE(PAPRSF_BUF, PAPHIF_BUF, PDELP_BUF, PR_BUF, PT_BUF, PQ_BUF, PQL_BUF, &
PQI_BUF, PU_BUF, PV_BUF, PVERVEL_BUF, PCP_BUF, PTKE_BUF, PQCPP_BUF, PNEBPP_BUF,&
PDIFCQ_BUF, PDIFCS_BUF, PFCCQL_BUF, PFCCQN_BUF, PPRODTH_BUF)

!Computations
DO NSTEP=1,NSTEPMAX
  WRITE(*,*)"NSTEP:",NSTEP
!$OMP PARALLEL DO PRIVATE(BLK_SIZE, D)
  DO K=1,NBLKS
    IF(K==NBLKS)THEN
      BLK_SIZE = LAST_BLK_NPROMA
    ELSE
      BLK_SIZE = NPROMA
    ENDIF
    D%NIT=MAX_BLK_SIZE
    D%NIB=KIDIA
    D%NIE=BLK_SIZE
    D%NKT=KLEV
    CALL ACVPPKF(YDCST,YDML_PHY_MF, CST, D, KTDIA, &
    & PAPRSF(:,:,K,NSTEP), PAPHIF(:,:,K,NSTEP), PDELP(:,:,K,NSTEP),  &
    & PR(:,:,K,NSTEP), PT(:,:,K,NSTEP), PQ(:,:,K,NSTEP), PQL(:,:,K,NSTEP), PQI(:,:,K,NSTEP), PU(:,:,K,NSTEP),&
    & PV(:,:,K,NSTEP), PVERVEL(:,:,K,NSTEP), PCP(:,:,K,NSTEP), PTKE(:,:,K,NSTEP), &
    & PDIFCQ(:,:,K,NSTEP), PDIFCS(:,:,K,NSTEP), PFCCQL(:,:,K,NSTEP), PFCCQN(:,:,K,NSTEP), PPRODTH(:,:,K,NSTEP), &
    & KNLAB(:,:,K,NSTEP), PQCPP(:,:,K,NSTEP), PNEBPP(:,:,K,NSTEP),&
    & KNND(:,K,NSTEP))
  ENDDO
!$OMP END PARALLEL DO
ENDDO

!Check results
DO NSTEP=1,NSTEPMAX
  DO K=1,NBLKS
    IF(K==NBLKS)THEN
      BLK_SIZE = LAST_BLK_NPROMA
    ELSE
      BLK_SIZE = NPROMA
    ENDIF
    DO J=0,KLEV
      DO I=1,BLK_SIZE
        IF(ORI_PDIFCQ(I+(K-1)*NPROMA,J,NSTEP) /= PDIFCQ(I,J,K,NSTEP))STOP 1
        IF(ORI_PDIFCS(I+(K-1)*NPROMA,J,NSTEP) /= PDIFCS(I,J,K,NSTEP))STOP 1
        IF(ORI_PFCCQL(I+(K-1)*NPROMA,J,NSTEP) /= PFCCQL(I,J,K,NSTEP))STOP 1
        IF(ORI_PFCCQN(I+(K-1)*NPROMA,J,NSTEP) /= PFCCQN(I,J,K,NSTEP))STOP 1
        IF(ORI_PPRODTH(I+(K-1)*NPROMA,J,NSTEP) /= PPRODTH(I,J,K,NSTEP))STOP 1
        IF(J>0)THEN
          IF(ORI_PQCPP(I+(K-1)*NPROMA,J,NSTEP) /= PQCPP(I,J,K,NSTEP))STOP 1
          IF(ORI_PNEBPP(I+(K-1)*NPROMA,J,NSTEP) /= PNEBPP(I,J,K,NSTEP))STOP 1
          IF(ORI_KNLAB(I+(K-1)*NPROMA,J,NSTEP) /= KNLAB(I,J,K,NSTEP))STOP 1
          IF(ORI_KNND(I+(K-1)*NPROMA,NSTEP) /= KNND(I,K,NSTEP))STOP 1
        ENDIF
      ENDDO
    ENDDO
  ENDDO
ENDDO
IF (LHOOK) CALL DR_HOOK('WRAP_ACVPPKF',1,ZHOOK_HANDLE)
END SUBROUTINE WRAP_ACVPPKF
