MODULE YOMHOOK

LOGICAL :: LHOOK = .FALSE.

CONTAINS

SUBROUTINE DR_HOOK (CDNAME, KCASE, PKEY)
USE OMP_LIB
CHARACTER (LEN=*) :: CDNAME
INTEGER :: KCASE
REAL*8, INTENT(INOUT)  :: PKEY

REAL*8 TEMP
IF(KCASE==1) THEN
  WRITE(*,*) "HOOK",OMP_GET_THREAD_NUM(), CDNAME, OMP_GET_WTIME()-PKEY
ELSE
  PKEY=OMP_GET_WTIME()
ENDIF

END SUBROUTINE
END MODULE
